name: Build Custom EPG from Your M3U (Google Drive)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: |
          pip install requests lxml gdown

      - name: Download playlist from Google Drive (robust)
        run: |
          set -euo pipefail
          gdown "https://drive.google.com/uc?id=1ycrzgwIoDsf_Rc11V3jj1D47mF33RTID" --output playlist.m3u
          echo "Playlist bytes: $(wc -c < playlist.m3u)"
          echo "First 5 lines:"
          head -n 5 playlist.m3u

      - name: Build epg.xml filtered to your channels
        run: |
          set -euo pipefail
          python <<'PY'
          import requests, re, sys
          from lxml import etree

          # Load playlist
          with open("playlist.m3u", encoding="utf-8", errors="ignore") as f:
              playlist = f.read()

          # Extract tvg-ids
          tvg_ids = sorted(set(re.findall(r'tvg-id="([^"]+)"', playlist)))
          print(f"Found {len(tvg_ids)} unique tvg-ids")

          # Fetch worldwide EPG
          epg_url = "https://iptv-org.github.io/epg/guides/all.xml"
          print(f"Downloading EPG from {epg_url}")
          r = requests.get(epg_url, timeout=60)
          r.raise_for_status()

          # Parse and filter
          parser = etree.XMLParser(recover=True)
          tree = etree.fromstring(r.content, parser=parser)

          tv_elem = etree.Element("tv")
          count = 0
          for elem in tree:
              if elem.tag == "channel":
                  if elem.get("id") in tvg_ids:
                      tv_elem.append(elem)
              elif elem.tag == "programme":
                  if elem.get("channel") in tvg_ids:
                      tv_elem.append(elem)
                      count += 1

          print(f"Kept {count} programmes for {len(tvg_ids)} channels")

          with open("epg.xml", "wb") as f:
              f.write(etree.tostring(tv_elem, pretty_print=True, xml_declaration=True, encoding="utf-8"))
          PY

      - name: Commit epg.xml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add epg.xml
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update EPG"
            git push
          fi
