name: Update EPG (worldwide, no credentials)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download worldwide EPG
        run: |
          set -e
          URL="https://iptv-org.github.io/epg/guides/all.xml"
          echo "Downloading EPG from $URL..."
          curl -fSL --retry 3 --retry-delay 5 "$URL" -o epg.xml
          echo "Downloaded size:"
          wc -c epg.xml
          echo "First 20 lines:"
          head -n 20 epg.xml

      - name: Commit epg.xml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add epg.xml
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update worldwide EPG"
            git push
          fi
