name: Build Custom EPG from Your M3U (Google Drive)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"   # daily 03:00 UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip lxml unidecode requests

      - name: Download playlist from Google Drive
        env:
          FILE_ID: "1ycrzgwIoDsf_Rc11V3jj1D47mF33RTID"
        run: |
          set -e
          # Robust Google Drive downloader (handles confirmation for large files)
          URL="https://drive.google.com/uc?export=download&id=${FILE_ID}"
          echo "Downloading playlist from Google Drive..."
          curl -c /tmp/cookies -fsSL "$URL" -o /tmp/intermediate.html || true
          CONFIRM=$(sed -n 's/.*confirm=\([0-9A-Za-z_]*\).*/\1/p' /tmp/intermediate.html | head -n 1)
          if [ -n "$CONFIRM" ]; then
            echo "Large file confirmation detected, using token..."
            curl -Lb /tmp/cookies -fsSL "https://drive.google.com/uc?export=download&confirm=${CONFIRM}&id=${FILE_ID}" -o playlist.m3u
          else
            # small file path (direct)
            curl -fsSL "$URL" -o playlist.m3u
          fi
          echo "Playlist size (bytes): $(wc -c < playlist.m3u)"

      - name: Build epg.xml filtered to your channels
        run: |
          python - << 'PY'
          import os, re, sys
          from unidecode import unidecode
          from lxml import etree
          import requests

          # ---------- helpers ----------
          def norm(s: str) -> str:
            if not s: return ""
            s = unidecode(s)
            s = s.strip().lower()
            s = re.sub(r"\s+", " ", s)
            return s

          # ---------- 1) parse playlist ----------
          pth = "playlist.m3u"
          if not os.path.exists(pth) or os.path.getsize(pth) == 0:
            print("ERROR: playlist.m3u missing or empty"); sys.exit(1)

          text = open(pth, "r", encoding="utf-8", errors="ignore").read()

          tvg_ids = set()
          names = set()

          for m in re.finditer(r'#EXTINF[^\n]*tvg-id="([^"]+)"[^\n]*,(.*)', text, flags=re.IGNORECASE):
            tvg_ids.add(m.group(1).strip())
            names.add(m.group(2).strip())

          for m in re.finditer(r'#EXTINF[^\n]*tvg-name="([^"]+)"[^\n]*,(.*)', text, flags=re.IGNORECASE):
            names.add(m.group(1).strip())
            names.add(m.group(2).strip())

          names_norm = {norm(n) for n in names if n}
          tvg_ids = {i for i in tvg_ids if i}

          print(f"Playlist: {len(tvg_ids)} tvg-ids; {len(names_norm)} names")

          # ---------- 2) infer countries & add a strong core ----------
          cc = set()
          for i in tvg_ids:
            if "." in i:
              tail = i.split(".")[-1].lower()
              if 2 <= len(tail) <= 3:
                cc.add(tail)

          core = {"fr","gb","us","de","es","it","nl","be","ch","pt","ca","br","ma","sa","eg","qa","ae","jp"}
          cc |= core
          print("Country feeds to try:", sorted(cc))

          # ---------- 3) name -> iptv-org id map ----------
          chan_url = "https://raw.githubusercontent.com/iptv-org/database/master/data/channels.json"
          print("Downloading channels.json ...")
          r = requests.get(chan_url, timeout=90)
          r.raise_for_status()
          db = r.json()
          name_to_ids = {}
          for ch in db:
            cid = ch.get("id")
            if not cid: continue
            if ch.get("name"):
              name_to_ids.setdefault(norm(ch["name"]), set()).add(cid)
            for nm in ch.get("names", []):
              name_to_ids.setdefault(norm(nm), set()).add(cid)

          keep_ids = set(tvg_ids)
          for n in names_norm:
            keep_ids |= name_to_ids.get(n, set())
          print("Will keep programmes for", len(keep_ids), "channel ids")

          # ---------- 4) download EPG country files ----------
          os.makedirs("epg_sources", exist_ok=True)
          downloaded = []
          for c in sorted(cc):
            url = f"https://raw.githubusercontent.com/iptv-org/epg/master/guides/{c}.xml"
            try:
              print("Fetch", url)
              r = requests.get(url, timeout=180)
              if r.status_code == 200 and r.content.strip():
                p = os.path.join("epg_sources", f"{c}.xml")
                open(p, "wb").write(r.content)
                downloaded.append(p)
                print(" OK", c, len(r.content), "bytes")
              else:
                print(" SKIP", c, r.status_code)
            except Exception as e:
              print(" ERR", c, e)

          if not downloaded:
            print("No EPG sources downloaded — writing minimal tv element.")
            open("epg.xml","wb").write(b'<?xml version="1.0" encoding="UTF-8"?><tv/>')
            sys.exit(0)

          # ---------- 5) merge only matching channels/programmes ----------
          root = etree.Element("tv")
          seen_channels = set()
          kept_prog = 0
          for p in downloaded:
            try:
              tv = etree.parse(p).getroot()
            except Exception as e:
              print("Bad XML", p, e); continue

            for ch in tv.findall("channel"):
              cid = ch.get("id")
              if cid in keep_ids and cid not in seen_channels:
                root.append(ch)
                seen_channels.add(cid)

            for pr in tv.findall("programme"):
              if pr.get("channel") in keep_ids:
                root.append(pr)
                kept_prog += 1

          out = etree.tostring(root, xml_declaration=True, encoding="UTF-8")
          open("epg.xml","wb").write(out)
          print(f"Written epg.xml with {len(seen_channels)} channels and {kept_prog} programmes")
          PY

      - name: Commit epg.xml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add epg.xml
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: build custom EPG from Google Drive playlist"
            git push
          fi
