name: Update EPG (worldwide, no credentials)

on:
  # Run manually from the Actions tab
  workflow_dispatch:
  # And automatically every day at 03:00 UTC
  schedule:
    - cron: "0 3 * * *"
  # Also run whenever you edit this file or push to main (optional but handy)
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/update-epg.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Download the big, worldwide XMLTV file and save as epg.xml
      - name: Download worldwide EPG
        run: |
          set -e
          curl -fsSL --retry 3 --retry-delay 3 \
            https://raw.githubusercontent.com/iptv-org/epg/master/guides/all.xml \
            -o epg.xml
          echo "Size (bytes): $(wc -c < epg.xml)"

      # Commit the file so your raw GitHub URL always serves the latest guide
      - name: Commit epg.xml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add epg.xml
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update worldwide EPG"
            git push
          fi
