name: Update EPG (worldwide, no credentials)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"   # daily at 03:00 UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip lxml

      # Try single worldwide feed first (covers ~all channels)
      - name: Try worldwide feed (all.xml)
        id: fetch_all
        run: |
          set -e
          URL="https://raw.githubusercontent.com/iptv-org/epg/master/guides/all.xml"
          echo "Downloading: $URL"
          curl -fsSL --retry 3 --retry-delay 3 "$URL" -o epg.xml || true
          if [ -f epg.xml ]; then
            SZ=$(wc -c < epg.xml || echo 0)
            echo "Downloaded epg.xml bytes: $SZ"
            # if > 500KB we consider it valid and skip fallback
            if [ "$SZ" -gt 512000 ]; then
              echo "use_all=true" >> "$GITHUB_OUTPUT"
            else
              echo "use_all=false" >> "$GITHUB_OUTPUT"
            fi
          else
            echo "use_all=false" >> "$GITHUB_OUTPUT"
          fi

      # If all.xml was too small/missing, build by countries (big list)
      - name: Prepare country list (fallback)
        if: steps.fetch_all.outputs.use_all == 'false'
        run: |
          cat > countries.txt << 'EOF'
          fr
          ma
          dz
          tn
          sa
          ae
          qa
          kw
          bh
          om
          eg
          lb
          jo
          il
          iq
          sy
          ye
          tr
          ir
          ng
          gh
          ke
          za
          cm
          sn
          ml
          ci
          ne
          tg
          bf
          gm
          mr
          es
          pt
          it
          de
          at
          ch
          nl
          be
          lu
          dk
          no
          se
          fi
          is
          ie
          gb
          pl
          cz
          sk
          hu
          ro
          bg
          gr
          rs
          ba
          hr
          si
          mk
          al
          mt
          cy
          ua
          lt
          lv
          ee
          ru
          by
          us
          ca
          mx
          br
          ar
          cl
          co
          pe
          uy
          py
          bo
          ec
          ve
          au
          nz
          in
          pk
          bd
          lk
          np
          my
          sg
          id
          ph
          th
          vn
          cn
          hk
          tw
          jp
          kr
          qa
          ae
          sa
          kw
          bh
          om
          eg
          il
          lb
          jo
          iq
          sy
          ye
          EOF
          sed -i '/^\s*$/d' countries.txt
          echo "Using $(wc -l < countries.txt) country feeds"

      - name: Download country feeds (fallback)
        if: steps.fetch_all.outputs.use_all == 'false'
        run: |
          mkdir -p epg_sources
          while read cc; do
            url="https://raw.githubusercontent.com/iptv-org/epg/master/guides/${cc}.xml"
            echo "Fetching $url"
            if curl -fsSL --retry 3 --retry-delay 3 "$url" -o "epg_sources/${cc}.xml"; then
              echo "OK: $cc"
            else
              echo "WARN: $cc not available"
            fi
          done < countries.txt
          ls -la epg_sources || true

      - name: Merge country feeds into epg.xml (fallback)
        if: steps.fetch_all.outputs.use_all == 'false'
        run: |
          python - << 'PY'
          import os
          from lxml import etree
          src = "epg_sources"
          files = [os.path.join(src,f) for f in os.listdir(src) if f.endswith(".xml")] if os.path.isdir(src) else []
          root = etree.Element("tv")
          seen = set()
          for f in files:
            try:
              tv = etree.parse(f).getroot()
            except Exception as e:
              print("Skip invalid", f, e); continue
            for ch in tv.findall("channel"):
              cid = ch.get("id")
              if cid and cid not in seen:
                root.append(ch); seen.add(cid)
            for pr in tv.findall("programme"):
              root.append(pr)
          with open("epg.xml","wb") as out:
            out.write(etree.tostring(root, xml_declaration=True, encoding="UTF-8"))
          print("Merged channels:", len(seen), "from files:", len(files))
          PY

      - name: Commit epg.xml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add epg.xml
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update worldwide EPG"
            git push
          fi
